### ISSUE TITLE
Error in function 'matting_laplacian'

### ISSUE THREAD

**Issue by iubunter** [luanfujun/deep-photo-styletransfer#39]
I got the error on the step2:

```
WARNING: Skipping content loss	
/torch/install/bin/luajit: deepmatting_seg.lua:291: invalid device function
stack traceback:
	[C]: in function 'matting_laplacian'
	deepmatting_seg.lua:291: in function 'MattingLaplacian'
	deepmatting_seg.lua:253: in function 'opfunc'
	/home/ubuntu/torch/install/share/lua/5.1/optim/lbfgs.lua:66: in function 'lbfgs'
	deepmatting_seg.lua:280: in function 'main'
	deepmatting_seg.lua:606: in main chunk
	[C]: in function 'dofile'
	...untu/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
```

Then I installed docker-version of program [here](https://github.com/martinbenson/deep-photo-styletransfer), but the error the same:

```
/root/torch/install/bin/luajit: /root/deep_photo/deepmatting_seg.lua:330: invalid device function
stack traceback:
	[C]: in function 'matting_laplacian'
	/root/deep_photo/deepmatting_seg.lua:330: in function 'MattingLaplacian'
	/root/deep_photo/deepmatting_seg.lua:284: in function 'opfunc'
	/root/torch/install/share/lua/5.1/optim/adam.lua:37: in function 'adam'
	/root/deep_photo/deepmatting_seg.lua:317: in function 'main'
	/root/deep_photo/deepmatting_seg.lua:645: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670
```

It looks like the problem in cuda_utils.cu:

```
__global__ void matting_laplacian_kernel(
	float *input, float *grad, int h, int w, 
	int *CSR_rowIdx, int *CSR_colIdx, float *CSR_val,
	int N
) { 
	printf(""I'm here now");  // It doesn't output in console
..
 }

int matting_laplacian(lua_State *L) {
...
	printf(""I'm here now");  // It prints

	matting_laplacian_kernel<<<(h*w-1)/TB+1, TB>>>(	
		THCudaTensor_data(state, input),
		THCudaTensor_data(state, grad),
		h, w,
		THCudaIntTensor_data(state, CSR_rowIdx),
		THCudaIntTensor_data(state, CSR_colIdx),
		THCudaTensor_data(state, CSR_val),
		N
	);

	checkCudaError(L); // It outputs error
```

I'd very appreciate any help!

**Comment by subzerofun** [comment]
Stupid question, but have you generated the Laplacian matrices with Matlab / Octave – are they saved in `/gen_laplacian/Input_Laplacian_3x3_1e-7_CSR[Image-Index].mat`?

Was just guessing because line of 291 in deepmatting_seg.lua:
`local grad = cuda_utils.matting_laplacian(output01, h, w, CSR_rowIdx, CSR_colIdx, CSR_val, N)`

But that is probably not the issue, since line 117 loads the .mat files:
`local CSR_fn = 'gen_laplacian/Input_Laplacian_'..tostring(params.patch)..'x'..tostring(params.patch)..'_1e-7_CSR' .. tostring(index) .. '.mat'`
If the .mat files were missing, you would already get stuck at this line.

Could you check your makefile if the paths / flags are correct? When i first compiled the file i didn't get any errors, but when i tried to run the code it crashed. The fix was adding `-lluajit` to `LDFLAGS_NVCC`, but this is only the case for OSX.

Since the docker version is failing (which has a working torch install + cuda drivers) there has to be something wrong with the cuda_utils.cu, or maybe your card/drivers/CUDA install files?

Which card do you use? The makefile has `-arch sm_35`so i'm not sure if older compute architectures are supported.

**Comment by iubunter** [comment]
Wow! Brilliant! I removed `-arch sm_35` and it've helped!
My card GeForce GTX 660 and that is the problem)
Thank you very much!
